
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/frauddb?useSSL=false&character_set_server=utf8mb4
#    username: root
    url:  jdbc:postgresql://localhost:5432/riskdb
    username: kid
    password: root
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080