
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/riskdb
    username: kid
    password: root
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    schemas: namematching
    baseline-on-migrate: true
server:
  port: 8080
