
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frauddb?useSSL=false&character_set_server=utf8mb4
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      idle-timeout: 30000
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080