
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/riskdb
    username: kid
    password: root
    hikari:
      connection-timeout: 10000
      leak-detection-threshold: 60000
      validation-timeout: 30000
      connection-test-query: SELECT 1;
      jdbc-url: jdbc:postgresql://localhost:5432/riskdb
      username: kid
      password: root
      data-source-properties: stringtype=unspecified
      maximum-pool-size: 16
      max-lifetime: 1800000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      pool-name: hikari.local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    schemas: namematching
    baseline-on-migrate: true
server:
  port: 8080

job.integration.vk.save:
  enabled: false